callstack/eslint-config-callstack

index.js
Fixes https://github.com/callstack/eslint-config-callstack-io/issues/21
=> feat: support .android.js and .ios.js extensions

index.js
Fixes https://github.com/callstack/eslint-config-callstack-io/issues/19
=> feat: disable import/prefer-default-export

.gitignore, README.md, index.js, package.json, yarn.lock
This ones I silent them in my test project:
```js
"react/destructuring-assignment": 0,
"prefer-destructuring": 0
```
This should not be happening:
```js
// eslint issue here: react/no-unused-state
state = {
index: 0,
routes: [
{ key: '1', title: I18n.t('available') },
{ key: '2', title: I18n.t('upcoming') },
{ key: '3', title: I18n.t('all') },
],
};
// eslint issue here: react/no-unused-state
_handleIndexChange = index => this.setState({ index });
<TabViewAnimated
navigationState={this.state}
...
/>
```
=> Make it compatible with eslint v5

index.js
Constants for OFF, WARNING and ERROR.
=> Improve Readability

index.js, package.json, yarn.lock
I've added the `eslint-plugin-react-native` package consistent with their [configuration guide](https://github.com/Intellicode/eslint-plugin-react-native#configuration).
This actually breaks the local test, since now this package becomes just for React Native.
=> Add `eslint-plugin-react-native`

index.js, package.json, test/index.js, test/package.json, test/yarn.lock, yarn.lock
- Adds hooks plugin
- Cleans up a bit
Fixup tests
=> feat: rules of hooks

index.js, package.json, test/.eslintrc, test/.eslintrc.js, test/__tests__/index.test.js, test/package.json, test/yarn.lock, yarn.lock
- remove airbnb config
- use `eslint:recommended`
- use `plugin:react/recommended `
- cleanup rules (verified what's inside both recommended sets)
- update some deps
Fixes #41 (not quite using `react-app` because it produces warnings around babel parser, but we're quite close I guess?)
Added some
=> feat: get rid of airbnb config; cleanup

index.js
=> fix: disable react/display-name

README.md, index.js, node.js, package.json, test/index.js, test/index.tsx, test/yarn.lock, yarn.lock
We are changing our internal eslint base ruleset from airbnb to callstack. One plugin that is missing that has helped us find real-world bugs is eslint-plugin-promise. I've added it here to reduce manual adjusting in dozens of app repos.
I also bumped the versions of packages to match known-good (no crashes or false positives) versions we have vetted internally.
1. Added code to test files based on real-world code that had promise warnings.
1. Ran `yarn test`, saw the failure I expected thanks to new promise rules.
1. Fixed new tests for promise rules based on internal fix for same warnings.
2. Ran `yarn test`, it passed.
=> Add eslint-plugin-promise and appropriate rules

package.json, yarn.lock
=> feat: bump eslint-plugin-jest to 22.6.4

package.json, yarn.lock
=> feat: bump eslint-plugin-flowtype to 3.9.1

package.json, yarn.lock
=> Greenkeeper/@typescript eslint/eslint plugin 1.10.2

.travis.yml, package.json, test/yarn.lock, yarn.lock
=> chore(package): update eslint-plugin-jest to version 22.10.0

package.json, test/yarn.lock, yarn.lock
Fix warnings related to eslint and security
`yarn test`
=> Upgrade packages

package.json, yarn.lock
chore(deps): bump eslint-plugin-react-native and bump publish package version
`yarn test`
=> bump eslint-plugin-react-native and bump publish package version

README.md, package.json, react-native.js, test/yarn.lock, yarn.lock
This is to resolve [issue #94 ](https://github.com/callstack/eslint-config-callstack/issues/94) with accessibility in mind
=> feat: add eslint-plugin-react-native-a11y 

node.js
Adds `import/order` set to error, since it's autofixable.
Fixes #98 
Not really
=> feat: add import/order

package.json, react-native.js, yarn.lock
=> feat: upgrade eslint-plugin-react-hooks to v4

package.json, test/index.tsx, yarn.lock
=> feat: update typescript parser

test/yarn.lock
This PR bundles 3 dependency updates indicated by dependabot for the `/test` folder. Changes made to `yarn.lock` only.
=> Bundle dependency updates for /test

node.js
Add new rule [`no-constant-binary-expression`](https://eslint.org/docs/latest/rules/no-constant-binary-expression)
`yarn eslint`
=> feat: Add `no-constant-binary-expression` rule
