callstack/eslint-config-callstack

- README.md
- index.js
Hey @satya164, got something for you
Summary:
* add `browser`, `node` and `es6` env
* add `jest/globals` env for test files matching default Jest's `testMatch` config
* setup `import/no-extraneous-dependencies` to work with tests
> Improve env setup; adjust import/no-extraneous-dependencies to tests

- index.js
Untranspiled files break in node with `trailingComma: 'all'`. Since this is a global config for all our callstack projects, it's better to have it as `es5` since we don't always transpile.
cc @grabbou
> Change trailing commas to es5

- .travis.yml
- package.json
- yarn.lock
I'm good with publishing manually, it's fairly easy with `yarn publish` and there are plans for `yarn commit` command which is supposed to ease generating changelogs, run CI and stuff.
> chore: drop semantic-release

- .travis.yml
- README.md
- package.json
- yarn.lock
We don't use npm 2 anywhere and it's about to get it's EOL soon. And missing peerDependencies in regular projects that use this config make Yarn (and probably npm 3+ too) unhappy.
Also, I'm tempted to remove semantic-release because it doesn't bump the version in `package.json`. It also released `0.5.0` to NPM registry without a git tag nor a changelog (here's link to some [weird errors](https://travis-ci.org/callstack/eslint-config-callstack-io/jobs/286465873) from CI)
> breaking: drop npm 2 support

- package.json
- yarn.lock
This changes a lot in formatting React components, so tagging it as breaking.
> breaking: bump Prettier to 1.7.4

- index.js
Due to usage of [`componentDidCatch()`](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html) in React 16, we should rather disable this rule. Often you don't need to use this in following class method.
> Remove class-methods-use-this rule

- package.json
- yarn.lock
This is mostly to overcome [a bug in ESLint 4.14](https://twitter.com/geteslint/status/944829414159810560)
Also bumped minors of prettier and `eslint-plugin-react` to fix #22
> chore: upgrade babel-eslint to v8

- index.js
- package.json
- yarn.lock
Right now eslint won't detect `jest` inside `__mocks__`.
> fix: add __mocks__ for jest

- README.md
- index.js
- node.js
Adds Node config without React and React Native specific plugins, envs and rules. The default config is for React and React Native and under-the-hood is using Node config, but tweaked.
`yarn test` is not failing, which means default config and Node config are valid.
> feature: add Node config

- package.json
We have an eslint-config package that depends on the @callstack/eslint-config, and adds a few overrides and eslint-plugin-react-redux. 
We had a need to update eslint-plugin-react to 7.13.0, which then requires  eslint-plugin-import  as a peerDependency. This means the apps have to add the import plugin to their package.json.
Bumping the package version here so the peerDependency is encapsulated here.
> feat: Bump eslint-plugin-react

- index.js
Discussed in #50.
The current rule being enabled can be noisy for perfectly fine code. There's a way to partially disable it, but consensus in issue #50 was to disable the rule altogether.
Resolved noise on an internal project.
> feat: Narrow react/no-multi-comp rule

- index.js
- test/index.js
In our codebase, we have this pattern:
```js
animate = (_: ?number) => {};
```
That triggers the unused-vars warning due to the argument being unused. In this instance, the argument is there to pass strong-type checks, and we have a code style guideline that uses prepending of underscore to signify  that the argument (or catch variable) is unused.
This PR adds a narrowing and widening of the no-unused-vars rule:
1.  to ignore unused arguments that begin with an underscore (a narrowing)
2. to report unused caught exceptions that don't begin with an underscore (a widening since unused caught errors was previously OFF by default)
Added code examples to test JS file, verified no errors.
> feat: Ignore args required for strong typing correctness

- index.js
I sifted through the numerous false positive issues, and added a reduction of one of our cases that seemed to match:
https://github.com/yannickcr/eslint-plugin-react/issues/1764
We ran into a few false positives with this rule, and it turns out there are over a dozen issues filed in eslint-plugin-react and a few unmerged PRs. Disabling it for now.
I can add an example to the JS files that would fire if the rule is enabled and the false positive isn't fix yet. Let me know if that's necessary to merge and I'll add it.
Will no longer fire on this code (a reduction of a production case):
```js
// @flow
import * as React from 'react';
type Props = {
maxItems: number,
itemOpacityOutputRange: Array<number>,
textOpacityOutputRange: Array<number>,
itemScaleOutputRange: Array<number>,
children: …
```
> feat: disable no-unused-prop-types rule

- index.js
We end up turning this off to better support:
-functional components, which are having default props deprecated
-it forces you to put in a value when you *want* undefined for field debuggability
-the hypothetical extra safety checking goes away when using a type checker like TypeScript or flow
> turn off react/require-default-props

- package.json
TypeScript 3.7 introduces nullish coalescing, optional chaining, and some other new syntax. To avoid false positives (nonsense lint warnings) due to prettier and other packages not understanding the new syntax, some packages need to be bumped.
> Support TypeScript 3.7

- node.js
- package.json
- test/.prettierrc
- test/index.js
- test/index.tsx
- test/yarn.lock
- yarn.lock
- Removes hard-coded Prettier config in favour of letting the Prettier find the config.
- Adds `@typescript-eslint/prefer-optional-chaining`
Updated the test files.
> feat(breaking): Infer Prettier config and add prefer-optional-chaining (breaking)

- .prettierrc
- README.md
- node.js
- react-native.js
- test/yarn.lock
We're applying Jest preset for all the files, which leads to situations where using globals like `expect`, `test` in project files is allowed. Or exporting functions from some files (spotted in snapshot-diff recently) is treated as an error.
This PR:
- extracts `TEST_PATTERNS` constant
- scopes Jest config to `TEST_PATTERNS` only
- adds `.prettierrc` to the project, hence formatting changes
- regenerates `yarn.lock` for test project, because I bumped into recently resolved ESLint issues (we should use workspaces and get over syncing like this)
- removes "browser env" references
Green CI
> feat: apply Jest config for tests only

- .travis.yml
- package.json
- test/yarn.lock
- yarn.lock
* bump prettier from 1.19.1 to 2.0.4
* bump eslint-config-prettier from 6.7.0 to 6.10.1
* bump eslint-plugin-prettier from 3.1.1 to 3.1.3
* add same node engine dependency as prettier
* update travis to test node 10, 12, node 8 no longer works with prettier
allows the use of new typescript syntax, which previously conflicted with older prettier versions.
ran yarn test.
i also tried on some of our internal repos that rely on eslint-config-callstack and it works great.
> feat(breaking): bump prettier

- node.js
- react-native.js
When using offical React Native CLI template for typescript (react-native-template-typescript) the CLI creates project with index.js file which imports App.tsx. Current @callstack/eslint-config did not support .js files importing .ts/.tsx files. I've changed the rule for react-native and node so that 
1. Create an empty React Native app using `npx react-native init AwesomeTSProject --template react-native-template-typescript`
2. Add @callstack/eslint-config using `yarn add --dev @callstack/eslint-config`
3. Run `yarn lint`
Using the current version it will fail with "Unable to resolve path to module './App'" for index.js.
PR version should work fine.
> Import extensions to support all extensions

- node.js
- package.json
- react.js
- yarn.lock
This PR removes requirement for consumers of this config to install parsers used within. Instead it will use babel config that user has in their project.
After recent update to the newest eslint parser changes in config forced users to install all parsers used in this project. This is a bit inconvenient as it makes developers install for example Flow parser even though they are not using it in their project.
Submitted changes are the attempt to fix and simplify setup for consumers of this config.
It was inspired by config created by @satya164.
https://github.com/satya164/eslint-config-satya164/blob/master/index.js
Install new config to a project and verify that rules are applied correctly.
> chore: do not require users to install parsers in their project

- package.json
- test/package.json
- test/yarn.lock
- yarn.lock
Major bumps:
- eslint-plugin-flowtype (requires eslint@^8.1, hence peer dep bump as well)
- eslint-plugin-promise
- eslint-plugin-react-native
- eslint-plugin-jest
New deps required as peers by `eslint-plugin-flowtype`:
- @babel/plugin-syntax-flow
- @babel/plugin-transform-react-jsx
No warnings related to this plugin. Known issue: https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/pull/145 (will be fixed when merged)
> chore(breaking): upgrade deps to match eslint 8

- package.json
- test/yarn.lock
- yarn.lock
Update typescript plugins versions as current version of the config still warns about unsupported TS version 5.8.2.
All checks pass.
> chore: update typescript

- react-native.js
'react-native-a11y/has-accessibility-hint' is too strict and incorrect in some cases.
I think it would be a good idea to turn it off by default.
https://github.com/FormidableLabs/eslint-plugin-react-native-a11y/issues/142
Pipelines pass.
> Disable 'react-native-a11y/has-accessibility-hint'

- .github/workflows/test.yml
- test/index.js
- test/index.tsx
`yarn test` was failing when running on `main`
CI job passes
> GitHub Actions test workflow

- node.js
- test/index.js
- test/index.tsx
Added the [require-await](https://eslint.org/docs/latest/rules/require-await) rule. Suggested here: https://github.com/callstack/reassure/pull/317#discussion_r1086427553
Modified `test/index.js` and `test/index.tsx`. CI should pass.
> chore: add `require-await` rule

- README.md
- node.js
- test/index.tsx
Added the [no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises/) rule.
`parserOptions` was modified because of this error:
Modified `test/index.tsx`. CI should pass.
> Add `no-floating-promises` rule

- README.md
The issue (#263) is that there is a little bit deprecated [suggestion](https://github.com/callstack/eslint-config-callstack#vscode) for VSCode settings config. Once I've added `@callstack/eslint-config` I saw a warning _(check a screenshot below)_. 
Looks like there was an update where `autoFix` started to be a default value. No sense to set it explicitly anymore. So I've updated `README.md`.
1. Add [@callstack/eslint-config](https://github.com/callstack/eslint-config-callstack#callstackeslint-config) to a project
2. Add [VSCode config](https://github.com/callstack/eslint-config-callstack#vscode) to your `.vscode/settings.json`
> fix: update vscode settings config of README.md

- test/no-constant-binary-expression.js
Add test for `no-constant-binary-expression` rule
```tsx
// comment out `'no-constant-binary-expression': ERROR,` in `node.js`
yarn test
// ^^^ should fail with the next errors:
//  - `Unused eslint-disable directive (no problems were reported from 'no-constant-binary-expression')`
```
> chore: Add tests for `no-constant-binary-expression`

- package.json
This pull request closes #272 
It adds both `homepage` and extended `repository` fields to the package config so that both links are visible in the npm page of the package.
> Include repo and homepage in the npm

- package.json
- react-native.js
- test/PlatformColor.js
- test/yarn.lock
- yarn.lock
- Enable [`@react-native/platform-colors`](https://github.com/facebook/react-native/blob/main/packages/eslint-plugin-react-native/README.md#platform-colors) rule
see: [`test/PlatformColor.js`](https://github.com/callstack/eslint-config-callstack/blob/7315d084116cc7cb84520348d21abd249271a8bc/test/PlatformColor.js)
> feat: Enable `@react-native/platform-colors` rule
